wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/tools/train.py
    python_version: 3.8.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686595683.792252
    t:
      1:
      - 1
      - 37
      - 41
      - 55
      - 60
      - 82
      2:
      - 1
      - 5
      - 37
      - 41
      - 53
      - 55
      - 60
      - 80
      - 82
      3:
      - 13
      - 23
      4: 3.8.16
      5: 0.15.4
      8:
      - 5
norm_cfg:
  desc: null
  value:
    type: SyncBN
    requires_grad: true
data_preprocessor:
  desc: null
  value:
    type: SegDataPreProcessor
    mean:
    - 71.02322328426814
    - 70.6379940200364
    - 71.67889280630872
    std:
    - 33.02850636286781
    - 32.481152762876164
    - 33.01011404576837
    bgr_to_rgb: true
    pad_val: 0
    seg_pad_val: 255
    size:
    - 1024
    - 1024
model:
  desc: null
  value:
    type: EncoderDecoder
    data_preprocessor:
      type: SegDataPreProcessor
      mean:
      - 71.02322328426814
      - 70.6379940200364
      - 71.67889280630872
      std:
      - 33.02850636286781
      - 32.481152762876164
      - 33.01011404576837
      bgr_to_rgb: true
      pad_val: 0
      seg_pad_val: 255
      size:
      - 1024
      - 1024
    pretrained: null
    backbone:
      type: MixVisionTransformer
      in_channels: 3
      embed_dims: 64
      num_stages: 4
      num_layers:
      - 3
      - 6
      - 40
      - 3
      num_heads:
      - 1
      - 2
      - 5
      - 8
      patch_sizes:
      - 7
      - 3
      - 3
      - 3
      sr_ratios:
      - 8
      - 4
      - 2
      - 1
      out_indices:
      - 0
      - 1
      - 2
      - 3
      mlp_ratio: 4
      qkv_bias: true
      drop_rate: 0.0
      attn_drop_rate: 0.0
      drop_path_rate: 0.1
      init_cfg:
        type: Pretrained
        checkpoint: pretrain/mit_b5.pth
    decode_head:
      type: SegformerHead
      in_channels:
      - 64
      - 128
      - 320
      - 512
      in_index:
      - 0
      - 1
      - 2
      - 3
      channels: 256
      dropout_ratio: 0.1
      num_classes: 4
      norm_cfg:
        type: SyncBN
        requires_grad: true
      align_corners: false
      loss_decode:
        type: CrossEntropyLoss
        use_sigmoid: false
        loss_weight: 1.0
    train_cfg: {}
    test_cfg:
      mode: slide
      crop_size:
      - 1024
      - 1024
      stride:
      - 768
      - 768
      decode_head:
        loss_decode:
          type: CrossEntropyLoss
          use_sigmoid: false
          loss_weight: 1.0
          class_weight:
          - 0.86219635
          - 0.83243454
          - 0.83369801
          - 0.99414109
dataset_type:
  desc: null
  value: Safeforest23CompressedDataset
data_root:
  desc: null
  value: /ofo-share/repos-david/Safeforest_CMU_data_dvc//data/site_Gascola/04_27_23/collect_04/processed_01/annotations/safeforest23_condensed
crop_size:
  desc: null
  value:
  - 1024
  - 1024
train_pipeline:
  desc: null
  value:
  - type: LoadImageFromFile
  - type: LoadAnnotations
  - type: RandomResize
    scale:
    - 2048
    - 1024
    ratio_range:
    - 0.5
    - 2.0
    keep_ratio: true
  - type: RandomCrop
    crop_size:
    - 512
    - 512
    cat_max_ratio: 0.75
  - type: RandomFlip
    prob: 0.5
  - type: PhotoMetricDistortion
  - type: PackSegInputs
test_pipeline:
  desc: null
  value:
  - type: LoadImageFromFile
  - type: Resize
    scale:
    - 2048
    - 1024
    keep_ratio: true
  - type: LoadAnnotations
  - type: PackSegInputs
img_ratios:
  desc: null
  value:
  - 0.5
  - 0.75
  - 1.0
  - 1.25
  - 1.5
  - 1.75
tta_pipeline:
  desc: null
  value:
  - type: LoadImageFromFile
    backend_args: null
  - type: TestTimeAug
    transforms:
    - - type: Resize
        scale_factor: 0.5
        keep_ratio: true
      - type: Resize
        scale_factor: 0.75
        keep_ratio: true
      - type: Resize
        scale_factor: 1.0
        keep_ratio: true
      - type: Resize
        scale_factor: 1.25
        keep_ratio: true
      - type: Resize
        scale_factor: 1.5
        keep_ratio: true
      - type: Resize
        scale_factor: 1.75
        keep_ratio: true
    - - type: RandomFlip
        prob: 0.0
        direction: horizontal
      - type: RandomFlip
        prob: 1.0
        direction: horizontal
    - - type: LoadAnnotations
    - - type: PackSegInputs
train_dataloader:
  desc: null
  value:
    batch_size: 1
    num_workers: 4
    persistent_workers: true
    sampler:
      type: InfiniteSampler
      shuffle: true
    dataset:
      type: Safeforest23CompressedDataset
      data_root: /ofo-share/repos-david/Safeforest_CMU_data_dvc//data/site_Gascola/04_27_23/collect_04/processed_01/annotations/safeforest23_condensed
      data_prefix:
        img_path: img_dir/train
        seg_map_path: ann_dir/train
      pipeline:
      - type: LoadImageFromFile
      - type: LoadAnnotations
      - type: RandomResize
        scale:
        - 2048
        - 1024
        ratio_range:
        - 0.5
        - 2.0
        keep_ratio: true
      - type: RandomCrop
        crop_size:
        - 512
        - 512
        cat_max_ratio: 0.75
      - type: RandomFlip
        prob: 0.5
      - type: PhotoMetricDistortion
      - type: PackSegInputs
val_dataloader:
  desc: null
  value:
    batch_size: 1
    num_workers: 4
    persistent_workers: true
    sampler:
      type: DefaultSampler
      shuffle: false
    dataset:
      type: Safeforest23CompressedDataset
      data_root: /ofo-share/repos-david/Safeforest_CMU_data_dvc//data/site_Gascola/04_27_23/collect_04/processed_01/annotations/safeforest23_condensed
      data_prefix:
        img_path: img_dir/val
        seg_map_path: ann_dir/val
      pipeline:
      - type: LoadImageFromFile
      - type: Resize
        scale:
        - 2048
        - 1024
        keep_ratio: true
      - type: LoadAnnotations
      - type: PackSegInputs
test_dataloader:
  desc: null
  value:
    batch_size: 1
    num_workers: 4
    persistent_workers: true
    sampler:
      type: DefaultSampler
      shuffle: false
    dataset:
      type: Safeforest23CompressedDataset
      data_root: /ofo-share/repos-david/Safeforest_CMU_data_dvc//data/site_Gascola/04_27_23/collect_04/processed_01/annotations/safeforest23_condensed
      data_prefix:
        img_path: img_dir/val
        seg_map_path: ann_dir/val
      pipeline:
      - type: LoadImageFromFile
      - type: Resize
        scale:
        - 2048
        - 1024
        keep_ratio: true
      - type: LoadAnnotations
      - type: PackSegInputs
val_evaluator:
  desc: null
  value:
    type: IoUMetric
    iou_metrics:
    - mIoU
    - mDice
    - mFscore
test_evaluator:
  desc: null
  value:
    type: IoUMetric
    iou_metrics:
    - mIoU
    - mDice
    - mFscore
default_scope:
  desc: null
  value: mmseg
env_cfg:
  desc: null
  value:
    cudnn_benchmark: true
    mp_cfg:
      mp_start_method: fork
      opencv_num_threads: 0
    dist_cfg:
      backend: nccl
vis_backends:
  desc: null
  value:
  - type: LocalVisBackend
  - type: WandbVisBackend
    init_kwargs:
      entity: safeforest-cmu
      project: mmsegmentation_gascola
      name: segformer_mit-b0_8xb1-160k_safeforest_gascola_23_04_27_collect_04
visualizer:
  desc: null
  value:
    type: SegLocalVisualizer
    vis_backends:
    - type: LocalVisBackend
    - type: WandbVisBackend
      init_kwargs:
        entity: safeforest-cmu
        project: mmsegmentation_gascola
        name: segformer_mit-b0_8xb1-160k_safeforest_gascola_23_04_27_collect_04
    name: visualizer
log_processor:
  desc: null
  value:
    by_epoch: false
log_level:
  desc: null
  value: INFO
load_from:
  desc: null
  value: null
resume:
  desc: null
  value: false
tta_model:
  desc: null
  value:
    type: SegTTAModel
optimizer:
  desc: null
  value:
    type: SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005
optim_wrapper:
  desc: null
  value:
    type: OptimWrapper
    optimizer:
      type: AdamW
      lr: 6.0e-05
      betas:
      - 0.9
      - 0.999
      weight_decay: 0.01
    paramwise_cfg:
      custom_keys:
        pos_block:
          decay_mult: 0.0
        norm:
          decay_mult: 0.0
        head:
          lr_mult: 10.0
param_scheduler:
  desc: null
  value:
  - type: LinearLR
    start_factor: 1.0e-06
    by_epoch: false
    begin: 0
    end: 1500
  - type: PolyLR
    eta_min: 0.0
    power: 1.0
    begin: 1500
    end: 20000
    by_epoch: false
train_cfg:
  desc: null
  value:
    type: IterBasedTrainLoop
    max_iters: 20000
    val_interval: 2000
val_cfg:
  desc: null
  value:
    type: ValLoop
test_cfg:
  desc: null
  value:
    type: TestLoop
default_hooks:
  desc: null
  value:
    timer:
      type: IterTimerHook
    logger:
      type: LoggerHook
      interval: 50
      log_metric_by_epoch: false
    param_scheduler:
      type: ParamSchedulerHook
    checkpoint:
      type: CheckpointHook
      by_epoch: false
      interval: 2000
    sampler_seed:
      type: DistSamplerSeedHook
    visualization:
      type: SegVisualizationHook
launcher:
  desc: null
  value: none
work_dir:
  desc: null
  value: ./work_dirs/segformer_mit-b5_8xb1-20k_safeforest_gascola_23_04_27_collect_04_compressed-1024x1024
